import { RE, rif, on, I18, delay } from '../RIF'

export const Editor = {
    replace: () => {

        if (!on.Editor) { return }

        const 编辑器 = {
            通用: [
                rif().class('content_yeu').class('header-label_H79'),
                rif().class('content_yeu').class('toggle-label_UK9'),
                rif().class('content_yeu').class('label_OqN'),
                rif().class('content_yeu').class('label_BbZ'),
                rif().class('picker-popup_pUb').class('name_u39'),
                rif().class('content_yeu.content_AD7').class('page-view_PUO').class('name_u39'),

                rif().class('content_yeu').class('label_tNr'),
                rif().class('content_yeu').class('picker-toggle_d6k'),
                rif().class('dropdown-item_Hjk'),
                rif().class('label_tNr'),
                rif().class('toggle-flags-button_T7X'),
                rif().class('header_IuN').class('title_zQN'),
                rif().class('button_WPv')
            ],

            通用inc: [
                rif({ match: 'inc' }).class('content_yeu').class('header-label_H79'),
                rif({ match: 'inc' }).class('content_yeu').class('toggle-label_UK9'),
                rif({ match: 'inc' }).class('content_yeu').class('label_OqN'),
                rif({ match: 'inc' }).class('content_yeu').class('label_BbZ'),
                rif({ match: 'inc' }).class('picker-popup_pUb').class('name_u39'),
                rif({ match: 'inc' }).class('content_yeu.content_AD7').class('page-view_PUO').class('name_u39'),

                rif({ match: 'inc' }).class('content_yeu').class('label_tNr'),
                rif({ match: 'inc' }).class('content_yeu').class('picker-toggle_d6k'),
                rif({ match: 'inc' }).class('dropdown-item_Hjk'),
                rif({ match: 'inc' }).class('label_tNr'),
                rif({ match: 'inc' }).class('toggle-flags-button_T7X')

            ],

            label: [
                rif().class('content_yeu').class('label_BbZ'),
                rif().class('content_yeu').class('label_OqN'),
            ]

        }
        return RE(
            编辑器.通用, {
            'Building Prefab': '建筑资产',
            'Meshes': '网格',
            'Mesh': '网格',
            'Position': '位置',
            'Rotation': '旋转',
            'Require State': '需求状态',
            'Circular': '圆形资产',
            'Access Type': '访问类型',
            'Lot Width': '区域宽度',
            'Lot Depth': '区域长度',
            'Name': '名称',
            'Front': '前',
            'LeftCorner': '左',
            'RightCorner': '右',
            'LeftAndRightCorner': '左/右',
            'LeftAndBackCorner': '左/后',
            'RightAndBackCorner': '右/后',
            'FrontAndBack': '前后',
            'All': '全部',

            'None': '无',
            'Child': '儿童',
            'Teen': '青少年',
            'Adult': '成年人',
            'Elderly': '老年人',
            'Dead': '死亡',
            'Stump': '树桩',
            'Empty': '空',
            'Full': '满',
            'Clear': '清理',
            'Track': '轨道',
            'Partial1': '部分1',
            'Partial2': '部分2',
            'LefthandTraffic': '左侧通行',
            'RighthandTraffic': '右侧通行',
            'Cold': '寒冷',
            'Warm': '温暖',
            'Home': '居住地',
            'Homeless': '无家可归',
            'Motorcycle': '摩托车',
            'Forward': '向前',
            'Backward': '向后',

            'Service Consumption': '服务消耗',
            'Upkeep': '维护',
            'Electricity Consumption': '电力消耗',
            'Water Consumption': '用水量',
            'Garbage Accumulation': '垃圾积累',
            'Telecom Need': '电信需求',

            'Placeable Object': '可放置对象',
            'Construction Cost': '建造费用',
            'XP Reward': '经验奖励',
            'Service Coverage': '服务覆盖范围',
            'Range': '范围',
            'Capacity': '容量',
            'Magnitude': '大小',
            'City Service Building': '城市服务建筑',
            'Upkeeps': '维护费用',
            'Park': '公园',
            'Maintenance Pool': '维护池',
            'Allow Homeless': '允许无家可归者',
            'Attraction': '吸引力',
            'Attractiveness': '吸引力',
            'Leisure Provider': '休闲提供',
            'Efficiency': '效率',
            'Leisure Type': '休闲类型',

            'UI Object': 'UI对象',
            'Group': '组',
            'Priority': '优先级',
            'Icon': '图标',
            'Large Icon': '大图标',
            'Is Debug Object': '是否为调试对象',
            'Administration': '行政管理',
            'AirTransportGroup': '航空运输组',
            'Areas': '区域',
            'AreasGroup': '区域组',
            'Budget': '预算',
            'Business': '业务',
            'CitizensCategory': '市民类别',
            'CityCategory': '城市类别',
            'CommunicationGroup': '通信组',
            'CommunicationsPost': '通信邮件',
            'CommunicationsTelecom': '通信电信',
            'CompanyCount': '公司数量',
            'Deathcare': '死亡护理',
            'DisasterControl': '灾难控制',
            'EconomyGroup': '经济组',
            'Education': '教育',
            'EducationGroup': '教育组',
            'ElectricityGroup': '电力组',
            'Employment': '就业',
            'Expenses': '支出',
            'Fire&RescueGroup': '消防和救援组',
            'GarbageManagement': '垃圾管理',
            'Happiness': '幸福',
            'Health&DeathcareGroup': '健康与殡葬',
            'Healthcare': '医疗保健',
            'HotelRooms': '酒店客房',
            'lmmaterial Goods': '非物质商品',
            'Income': '收入',
            'InfoViewGroup': '信息视图组',
            'InfoViewsCategory': '信息视图类别',
            'Interface&ToolsCategory': '界面和工具类别',
            'Jobs': '工作',
            'LandscapingGroup': '景观组',
            'LargeParks': '大型公园',
            'LargeSportsParks': '大型体育公园',
            'MapTileGroup': '地图瓦片组',
            'Marker Object Prefabs': '标记对象资产',
            'Material Goods': '物质商品',
            'Materials': '材料',
            'NotificationsGroup': '通知组',
            'Parks&RecreationGroup': '公园与娱乐组',
            'Pathways': '路径',
            'PhotoModeGroup': '照片模式组',
            'Police': '警察',
            'Police&AdministrationGroup': '警察与行政组',
            'Population': '人口',
            'PopulationDecline': '人口减少',
            'PopulationGrowth': '人口增长',
            'Post': '邮政',
            'ProgressionGroup': '进展组',
            'PublicTransport': '公共交通',


            'Object Sub Objects': '对象 - 子物件',
            'Object Sub Nets': '对象 - 子网',
            'Invert When': '反转条件',
            'Sub Nets': '子线段',
            'Net Prefab': '线段资产',
            'Bezier Curve': '贝塞尔曲线',
            'Node Index': '节点索引',
            'Parent Mesh': '父网格',
            'Upgrades': '升级',
            'Sub Objects': '子对象',
            'Object': '对象',
            'Group Index': '组索引',
            'Probability': '概率',

            'Effect Source': '效果源',
            'Effects': '效果',
            'Animation Curves': '动画曲线',
            'Effect': '效果',
            'Position Offset': '位置偏移',
            'Scale': '比例',
            'Intensity': '强度',
            'AnimationIndex': '动画索引',
            'Unlockable': '可解锁',
            'Require All': '需要全部',
            'Require Any': '需要任意',
            'Ignore Dependencies': '忽略依赖关系',
            'Object Sub Areas': '对象 - 子区域',
            'Sub Areas': '子区域',
            'Area Prefab': '区域资产',
            'Node Positions': '节点位置',
            'Parent Meshes': '父网格',

            'Resources': '资源',
            'Resource': '资源',
            'Amount': '数量',
            'Scale With Usage': '使用比例缩放',
            'Pollution': '污染',
            'Ground Pollution': '地面污染',
            'Air Pollution': '空气污染',
            'Noise Pollution': '噪音污染',
            'Scale With Renters': '随租客数量缩放',
            'Transport Station': '交通站点',
            'Car Refuel Types': '汽车加油类型',
            'Train Refuel Types': '火车加油类型',
            'Watercraft Refuel Types': '水上交通工具加油类型',
            'Aircraft Refuel Types': '飞机加油类型',
            'Comfort Factor': '舒适因子',
            'Fuel': '燃料',
            'FuelAndElectricity': '燃料和电力',
            'Obsolete Identifiers': '已过时标识符',
            'Building Terraform Override': '建筑地形改造覆盖',
            'Level Min Offset': '平整最小偏移',
            'Level Max Offset': '平整最大偏移',
            'Level Front Left': '左前平整',
            'Level Front Right': '右前平整',
            'Level Back Left': '左后平整',
            'Level Back Right': '右后平整',
            'Smooth Min Offset': '平滑最小偏移',
            'Smooth Max Offset': '平滑最大偏移',
            'Height Offset': '高度偏移',
            'Additional Smooth Areas': '额外平滑区域',
            'Dont Raise': '不提升',
            'Dont Lower': '不降低',
            'School': '学校',
            'Student Capacity': '学生容量',
            'Level': '等级',
            'Graduation Modifier': '毕业修改器',
            'Student Wellbeing': '学生生活质量',
            'Student Health': '学生健康',
            'Service Fee Collector': '服务费收集器',
            'Object Sub Lanes': '对象 - 子线段',
            'Sub Lanes': '子车道',
            'Lane Prefab': '车道资产',
            'Prison': '监狱',
            'Prison Van Capacity': '监狱车辆容量',
            'Prisoner Capacity': '囚犯容量',
            'Prisoner Wellbeing': '囚犯福祉',
            'Prisoner Health': '囚犯健康',
            'Local Effects': '局部影响',
            'Type': '类型',
            'Mode': '模式',
            'Delta': '增量',
            'Radius Combine Mode': '半径组合模式',
            'Radius': '半径',
            'Prefab Identifiers': '资产标识符',
            'Power Plant': '发电厂',
            'Electricity Production': '电力生产',
            'Resource Consumer': '资源消耗',
            'No Resource Notification Prefab': '无资源通知 资产',
            'Storage Limit': '存储限制',

            'Spawnable Building': '自长建筑',
            'Zone Type': '区域类型',
            'Building Properties': '建筑属性',
            'Residential Properties': '住宅属性',
            'Allowed Sold': '允许销售',
            'Allowed Manufactured': '允许制造',
            'Allowed Stored': '允许存储',
            'Space Multiplier': '空间倍增',
            'NoResource': '无资源',
            'Money': '金钱',
            'Grain': '粮食',
            'ConvenienceFood': '便利食品',
            'Food': '食物',
            'Vegetables': '蔬菜',
            'Meals': '餐点',
            'Wood': '木材',
            'Timber': '木材',
            'Paper': '纸张',
            'Furniture': '家具',
            'Vehicles': '车辆',
            'Lodging': '住宿',
            'UnsortedMail': '未分类邮件',
            'LocalMail': '本地邮件',
            'OutgoingMail': '外发邮件',
            'Oil': '石油',
            'Petrochemicals': '石化产品',
            'Ore': '矿石',
            'Plastics': '塑料',
            'Metals': '金属',
            'Electronics': '电子产品',
            'Software': '软件',
            'Coal': '煤炭',
            'Stone': '石头',
            'Livestock': '牲畜',
            'Cotton': '棉花',
            'Steel': '钢铁',
            'Minerals': '矿物',
            'Concrete': '混凝土',
            'Machinery': '机械',
            'Chemicals': '化学品',
            'Pharmaceuticals': '药品',
            'Beverages': '饮料',
            'Textiles': '纺织品',
            'Telecom': '电信',
            'Financial': '金融',
            'Media': '媒体',
            'Entertainment': '娱乐',
            'Recreation': '娱乐',
            'Garbage': '垃圾',
            'Count': '数量',
            'Static Object Prefab': '静态对象资产',
            'Tree Objec': '树木对象',
            'Wood Amount': '木材数量',
            'Standing Object': '站立对象',
            'Leg Size': '根部尺寸',
            'Circular Leg': '圆形根部',
            'Sub Object Default Probability': '子对象默认概率',
            'Default Probability': '默认概率',
            'Rotation Symmetry': '旋转对称',
            'Car Prefab': '汽车资产',
            'Size Class': '尺寸类别',
            'Energy Type': '能源类型',
            'Max Speed': '最大速度',
            'Acceleration': '加速度',
            'Braking': '刹车',
            'Turning': '转向',
            'Stiffness': '刚度',
            'Small': '小型',
            'Medium': '中型',
            'Large': '大型',
            'Personal Car': '私家车',
            'Passenger Capacity': '乘客容量',
            'Baggage Capacity': '行李容量',
            'Cost To Drive': '驾驶成本',
            'Vehicle Side Effects': '车辆副作用',
            'Road Wear': '路面磨损',
            'Activity Location': '活动位置',
            'Locations': '位置',
            'Animated Prop Name': '动画道具名称',
            'Require Authorization': '需要授权',
            'Activity': '活动',
            'Bench Sitting Location': '长椅坐着位置',
            'Boarding Location': '上车位置',
            'Disembarking Location': '下车位置',
            'Driving Location': '驾驶位置',
            'Entrance Location': '入口位置',
            'Garage Spot Location': '车库停车位位置',
            'Producing Location': '生产位置',
            'PullUp Location': '停靠位置',
            'Road Prefab': '道路资产',
            'Sections': '区段',
            'Node': '节点',
            'Intersection': '交叉路口',
            'DeadEnd': '死胡同',
            'Crosswalk': '人行横道',
            'BusStop': '公交车站',
            'Median': '中央分隔带',
            'TrainStop': '火车站',
            'OppositeTrainStop': '对面火车站',
            'Inverted': '倒置',
            'TaxiStand': '出租车站',
            'LevelCrossing': '道路平交道',
            'Elevated': '高架',
            'Tunnel': '隧道',
            'Raised': '高起',
            'Lowered': '下降',
            'LowTransition': '低过渡',
            'HighTransition': '高过渡',
            'WideMedian': '宽中央分隔带',
            'TramTrack': '有轨电车轨道',
            'TramStop': '有轨电车站',
            'OppositeTramTrack': '对面有轨电车轨道',
            'OppositeTramStop': '对面有轨电车站',
            'MedianBreak': '中央分隔带中断',
            'ShipStop': '船只停靠点',
            'Sidewalk': '人行道',
            'Edge': '边缘',
            'SubwayStop': '地铁站',
            'OppositeSubwayStop': '对面地铁站',
            'MiddlePlatform': '中间站台',
            'Underground': '地下',
            'Roundabout': '环形交叉口',
            'OppositeSidewalk': '对面人行道',
            'SoundBarrier': '隔音墙',
            'Overhead': '架空',
            'PublicTransportLane': '公共交通车道',
            'OppositePublicTransport': '对面公共交通',
            'Spillway': '泄洪道',
            'MiddleGrass': '中央草地',
            'MiddleTrees': '中央树木',
            'WideSidewalk': '宽人行道',
            'SideGrass': '边缘草地',
            'SideTrees': '边缘树木',
            'OppositeGrass': '对面草地',
            'OppositeTrees': '对面树木',
            'Opening': '开口',
            'Back': '后方',
            'Flipped': '翻转',
            'RemoveTrafficLights': '移除交通信号灯',
            'AllWayStop': '四路停车标志',
            'Pavement': '人行道',
            'Gravel': '碎石路',
            'Tiles': '瓷砖',
            'ForbidLeftTurn': '禁止左转',
            'ForbidRightTurn': '禁止右转',
            'OppositeWideSidewalk': '对面宽人行道',
            'OppositeForbidLeftTurn': '对面禁止左转',
            'OppositeForbidRightTurn': '对面禁止右转',
            'OppositeSoundBarrier': '对面隔音墙',
            'SidePlatform': '侧面站台',
            'AddCrosswalk': '添加人行横道',
            'RemoveCrosswalk': '移除人行横道',
            'Lighting': '照明',
            'OppositeBusStop': '对面公交站',
            'OppositeTaxiStand': '对面出租车站',
            'OppositeRaised': '对面高起',
            'OppositeLowered': '对面下降',
            'OppositeLowTransition': '对面低过渡',
            'OppositeHighTransition': '对面高过渡',
            'OppositeShipStop': '对面船只停靠点',
            'OppositePlatform': '对面站台',
            'OppositeAddCrosswalk': '对面添加人行横道',
            'OppositeRemoveCrosswalk': '对面移除人行横道',
            'Inside': '内部',
            'ForbidStraight': '禁止直行',
            'OppositeForbidStraight': '对面禁止直行',
            'Require None': '需要 不存在:',
            'Invert': '反转',
            'Flip': '翻转',
            'Offset': '偏移',
            'Set State': '设置状态',
            'Match Type': '匹配类型',
            'Both': '两者',
            'Any': '任意',
            'Exclusive': '唯一',
            'Max Slope Steepness': '最大坡度陡峭程度',
            'Aggregate Type': '聚合类型',
            'Invert Mode': '反转模式',
            'Road Type': '道路类型',
            'Speed Limit': '速度限制',
            'Zone Block': '区块',
            'Highway Rules': '高速公路规则',
            'InvertLefthandTraffic': '反转左侧交通',
            'FlipLefthandTraffic': '翻转左侧交通',
            'InvertRighthandTraffic': '反转右侧交通',
            'FlipRighthandTraffic': '翻转右侧交通',
            'KeepOriginal': '保留原始',
            'Alley': '巷子',
            'Bridge': '桥梁',
            'Dam': '大坝',
            'Grand Bridge': '大桥',
            'Highway': '高速公路',
            'Invisible Pathway': '隐形路径',
            'Pathway': '小径',
            'Public Transport Lane': '公共交通车道',
            'Runway': '跑道',
            'Seaway': '航道',
            'Street': '街道',
            'Subway Track': '地铁轨道',
            'Taxiway': '滑行道',
            'Train Track': '铁路',
            'Tram Track': '有轨电车轨道',
            'Placement': '放置',
            'FixedIndex': '固定索引',
            'Anchor Top': '锚定顶部',
            'Anchor Center': '锚定中心',
            'Require Elevated': '需要高架',
            'Require Outside Connection': '需要市外连接',
            'Require Dead End': '需要死胡同',
            'Require Orphan': '需要孤立',
            'Placeable Net': '可放置道路',
            'Elevation Range': '高度范围',
            'Allow Parallel Mode': '允许并列模式',
            'Underground Prefab': '地下资产',
            'Electricity Connection': '电力连接',
            'Voltage': '电压',
            'Direction': '方向',
            'Low': '低',
            'High': '高',
            'Invalid': '无效',
            'Select Nothing/Everything': '选择无/全部',
            'Water Pipe Connection': '水管连接',
            'Fresh Capacity': '清水容量',
            'Sewage Capacity': '污水容量',
            'Storm Capacity': '雨水容量',
            'Net Pollution': '道路污染',
            'Noise Pollution Factor': '噪音污染因子',
            'Air Pollution Factor': '空气污染因子',
            'Underground Net Sections': '地下道路部分',
            'Unlock On Build': '依赖建筑解锁',
            'Deathcare Facility': '丧葬设施',
            'Hearse Capacity': '救护车容量',
            'Storage Capacity': '存储容量',
            'Processing Rate': '处理速率',
            'Long Term Storage': '长期存储',
            'Workplace': '工作场所',
            'Workplaces': '工作场所',
            'Complexity': '复杂度',
            'Evening Shift Probability': '晚班概率',
            'Night Shift Probability': '夜班概率',
            'Manual': '手动',
            'Simple': '简单',
            'Complex': '复杂',
            'Hitech': '高科技',
            'Commercial': '商业',
            'Citylndoors': '城市室内',
            'Travel': '旅行',
            'CityPark': '城市公园',
            'CityBeach': '城市海滩',
            'Attractions': '景点',
            'Relaxation': '放松',
            'Sightseeing': '观光',
            'Never': '从不',
            'Unlocks': '解锁',
            'Company Object': '公司对象',
            'Select Company': '选择公司',
            'Companies': '公司',
            'Commercial_Bar': '商业_酒吧',
            'Commercial_BookStore': '商业_书店',
            'Commercial_ChemicalStore': '商业_化学品商店',
            'Commercial_ConvenienceFoodStore': '商业_便利食品店',
            'Commercial_DrugStore': '商业_药店',
            'Commercial_ElectronicsStore': '商业_电子产品商店',
            'Commercial_FashionStore': '商业_时装店',
            'Commercial_FoodStore': '商业_食品商店',
            'Commercial_FurnitureStore': '商业_家具商店',
            'Commercial_GasStation': '商业_加油站',
            'Commercial_Hotel': '商业_酒店',
            'Commercial_LiquorStore': '商业_酒水店',
            'Commercial_PlasticsStore': '商业_塑料制品商店',
            'Commercial_RecreactionStore': '商业_娱乐用品店',
            'Commercial_Restaurant': '商业_餐厅',
            'Commercial_VehicleStore': '商业_车辆商店',
            'Industrial_BeverageFromGrainFactory': '工业_谷物饮料工厂',
            'Industrial_BeverageFromVegetablesFactory': '工业_蔬菜饮料工厂',
            'Industrial_BioRefinery': '工业_生物炼制厂',
            'Industrial_ChemicalFactory': '工业_化学品工厂',
            'Industrial_CoalMine': '工业_煤矿',
            'Industrial_ConcreteFactory': '工业_混凝土工厂',
            'Industrial_ConvenienceFoodFromGrainFactory': '工业_便利食品(从谷物)工厂',
            'Industrial_ConvenienceFoodFromLivestockFactory': '工业_便利食品(从牲畜)工厂',
            'Industrial_CottonExtractor': '工业_棉花提取器',
            'Industrial_ElectronicsFactory': '工业_电子产品工厂',
            'Industrial_FoodFactory': '工业_食品工厂',
            'Industrial_ForestryExtractor': '工业_林业提取器',
            'Industrial_FurnitureFactory': '工业_家具工厂',
            'Industrial_GrainExtractor': '工业_谷物提取器',
            'Industrial_LivestockExtractor': '工业_牲畜提取器',
            'Industrial_MachineryFactory': '工业_机械工厂',
            'Industrial_MetalSmelter': '工业_金属冶炼厂',
            'Industrial_MineralPlant': '工业_矿产加工厂',
            'Industrial_OilExtractor': '工业_石油提取器',
            'Industrial_OilRefinery': '工业_石油精炼厂',
            'Industrial_OreExtractor': '工业_矿石提取器',
            'Industrial_PaperMill': '工业_造纸厂',
            'Industrial_PharmaceuticalsFactory': '工业_制药厂',
            'Industrial_PlasticsFactory': '工业_塑料制品工厂',
            'Industrial_SawMill': '工业_锯木厂',
            'Industrial_SteelPlant': '工业_钢铁厂',
            'Industrial_StoneQuarry': '工业_石材采石场',
            'Industrial_TextileFromCottonFactory': '工业_纺织品(从棉花)工厂',
            'Industrial_TextileFromLivestockFactory': '工业_纺织品(从牲畜)工厂',
            'Industrial_TextileFromPetrochemicalsFactory': '工业_纺织品(从石油化工产品)工厂',
            'Industrial_VegetableExtractor': '工业_蔬菜提取器',
            'Industrial_VehicleFactory': '工业_车辆工厂',
            'Industrial_WarehouseBeverages': '工业_饮料仓库',
            'Industrial_WarehouseChemicals': '工业_化学品仓库',
            'Industrial_WarehouseCoal': '工业_煤仓库',
            'Industrial_WarehouseConcrete': '工业_混凝土仓库',
            'Industrial_WarehouseConvenienceFood': '工业_便利食品仓库',
            'Industrial_WarehouseCotton': '工业_棉花仓库',
            'Industrial_WarehouseElectronics': '工业_电子产品仓库',
            'Industrial_WarehouseFood': '工业_食品仓库',
            'Industrial_WarehouseFurniture': '工业_家具仓库',
            'Industrial_WarehouseGrain': '工业_谷物仓库',
            'Industrial_WarehouseLivestock': '工业_牲畜仓库',
            'Industrial_WarehouseMachinery': '工业_机械仓库',
            'Industrial_WarehouseMetals': '工业_金属仓库',
            'Industrial_WarehouseMinerals': '工业_矿产仓库',
            'Industrial_WarehouseOil': '工业_石油仓库',
            'Industrial_WarehouseOre': '工业_矿石仓库',
            'Industrial_WarehousePaper': '工业_纸张仓库',
            'Industrial_WarehousePetrochemicals': '工业_石化产品仓库',
            'Industrial_WarehousePharmaceuticals': '工业_制药产品仓库',
            'Industrial_WarehousePlastics': '工业_塑料仓库',
            'Industrial_WarehouseSteel': '工业_钢铁仓库',
            'Industrial_WarehouseStone': '工业_石材仓库',
            'Industrial_WarehouseTextiles': '工业_纺织品仓库',
            'Industrial_WarehouseTimber': '工业_木材仓库',
            'Industrial_WarehouseVegetables': '工业_蔬菜仓库',
            'Industrial_WarehouseVehicles': '工业_车辆仓库',
            'Industrial_WarehouseWood': '工业_木材仓库',
            'Office_Bank': '办公_银行',
            'Office_MediaCompany': '办公_传媒公司',
            'Office_SoftwareCompany': '办公_软件公司',
            'Office_TelecomCompany': '办公_电信公司',
            'Fire Station': '消防站',
            'Fire Engine Capacity': '消防车辆容量',
            'Fire Helicopter Capacity': '消防直升机容量',
            'Disaster Response Capacity': '灾害响应容量',
            'Vehicle Efficiency': '车辆效率',
            'Transformer': '变压器',
            'Solar Powered': '太阳能供电',
            'Production': '生产',
            'Battery': '电池',
            'Power Output': '功率输出',
            'Water Pumping Station': '水泵站',
            'Purification': '净化',
            'Allowed Water Types': '允许的水类型',
            'Groundwater': '地下水',
            'SurfaceWater': '地表水',
            'Shoreline Object': '岸线物体',
            'Shoreline Offset': '岸线偏移',
            'Allow Dryland': '允许干地',
            'Service Upgrade': '服务升级',
            'Buildings': '建筑物',
            'Upgrade Cost': '升级成本',
            'Max Placement Offset': '最大放置偏移',
            'Public Transport': '公共交通',
            'Transport Type': '运输类型',
            'Purposes': '用途',
            'Maintenance Range': '维护范围',
            'Bus': '公共汽车',
            'Train': '火车',
            'Taxi': '出租车',
            'Tram': '有轨电车',
            'Ship': '船',
            'Helicopter': '直升飞机',
            'Airplane': '飞机',
            'Subway': '地铁',
            'Rocket': '火箭',
            'TransportLine': '运输线路',
            'Evacuation': '疏散',
            'PrisonerTransport': '囚犯运输',
            'Other': '其他',
            'Gender': '性别',
            'Move Speed': '移动速度',
            'Domesticated': '驯化',
            'Idle Time': '空闲时间',
            'Min Group Member Count': '最小组成员数',
            'Max Group Member Count': '最大组成员数',
            'Spawnable Object': '可生成对象',
            'Placeholders': '占位符',
            'Randomization Group': '随机化组',
            'Selected Sound': '选择声音',
            'Bear Species': '熊种',
            'Chicken Species': '鸡种',
            'Cow Species': '牛种',
            'Deer Species': '鹿种',
            'Dolphin Species': '海豚种',
            'Eagle Species': '鹰种',
            'Goose Species': '鹅种',
            'Horse Species': '马种',
            'Moose Species': '驼鹿种',
            'PergolaStyle01': '凉亭风格01',
            'Pig Species': '猪种',
            'Seagull Species': '海鸥种',
            'Shark Species': '鲨鱼种',
            'Sheep Species': '绵羊种',
            'Sidewalk Prop Group': '人行道道具组',
            'Marker Object Prefab': '标记对象资产',
            'Creature Spawner': '生物生成器',
            'Max Group Count': '最大组数',
            'Spawn Location': '生成位置',
            'Connection Type': '连接类型',
            'Track Types': '轨道类型',
            'Road Types': '道路类型',
            'Road': '道路',
            'Pedestrian': '行人',
            'Cargo': '货物',
            'Air': '空中',
            'Parking': '停车',
            'Car': '汽车',
            'Watercraft': '水上交通工具',
            'Editor Asset Category Override': '编辑器资产类别覆盖',
            'Include Categories': '包括类别',
            'Exclude Categories': '排除类别',
            'Attached Object': '附加对象',
            'Attach Type': '附加类型',
            'Attach Offset': '附加偏移',
            'Animation Index': '动画索引',
            'Street Light Object': '路灯对象',
            'PDXAccount': 'p社账号',
            'BeachProperties': '海滩DLC',
            'Localization': '本地化',
            'Objects': '对象',
            'Policies': '政策',
            'Prefabs': '资产',
            'Routes': '路线',
            'Themes': '主题',
            'Tools': '工具',
            'UI': '用户界面',
            'Achievement Filter': '成就过滤器',
            'Object Achievement Component': '对象成就组件',
            'Building Efficiency': '建筑效率',
            'City Effects': '城市效应',
            'CityServices': '城市服务',
            'Extractor Facility': '提取设施',
            'Initial Resources': '初始资源',
            'Placeholder Building': '占位建筑',
            'Pollution Modifier': '污染修正器',
            'Resource Consumption': '资源消耗',
            'Resource Producer': '资源生产者',
            'Signature Building': '标志性建筑',
            'Random Gendered Localization': '随机性别本地化',
            'Random Localization': '随机本地化',
            'Brand Object': '品牌对象',
            'Crane Object': '起重机对象',
            'Destructible Object': '可摧毁对象',
            'Electricity Outside Connection': '电力外部连接',
            'Floating Object': '漂浮物体',
            'Hovering Object': '悬浮物体',
            'Lane Block': '车道阻塞',
            'Lane Direction Object': '车道方向对象',
            'Net Object': '道路对象',
            'Outside Connection': '外部连接',
            'Pillar Object': '柱状物体',
            'Placeholder Object': '占位对象',
            'Plant Object': '植物对象',
            'Quantity Object': '数量对象',
            'Renter Object': '租户对象',
            'Spawnable Brand Dummy': '可生成品牌虚拟',
            'Traffic Light Object': '交通灯对象',
            'Traffic Sign Object': '交通标志对象',
            'Tree Object': '树木对象',
            'Underwater Object': '水下对象',
            'Unique Object': '独特对象',
            'Utility Object': '实用对象',
            'Water Pipe Outside Connection': '水管外部连接',
            'Water Source': '水源',
            'Weather Object': '天气对象',
            'Default Policies': '默认政策',
            'Content': '内容',
            'To Be Removed': '待删除',
            'Unlocking': '解锁',
            'Mail Box': '邮箱',
            'Transport Stop': '交通站',
            'Theme Object': '主题对象',
            'Editor Container': '编辑器容器',
            'Valid For': '有效',
            'Not Valid For': '无效',
            'Relative': '相对',
            'Absolute': '绝对',
            'InverseRelative': '反向相对',
            'CrimeAccumulation': '犯罪累积',
            'DisasterWarningTime': '灾害警告时间',
            'DisasterDamageRate': '灾害伤害率',
            'DiseaseProbability': '疾病概率',
            'ParkEntertainment': '公园娱乐',
            'CriminalMonitorProbability': '犯罪监视概率',
            'IndustrialAirPollution': '工业空气污染',
            'IndustrialGroundPollution': '工业地面污染',
            'IndustrialGarbage': '工业垃圾',
            'RecoveryFailChange': '恢复失败机率',
            'OreResourceAmount': '矿石资源量',
            'OilResourceAmount': '石油资源量',
            'UniversityInterest': '大学兴趣',
            'OfficeSoftwareDemand': '办公软件需求',
            'IndustrialElectronicsDemand': '工业电子产品需求',
            'OfficeSoftwareEfficiency': '办公软件效率',
            'IndustrialElectronicsEfficiency': '工业电子产品效率',
            'TelecomCapacity': '电信容量',
            'HighwayTrafficSafety': '高速公路交通安全',
            'PrisonTime': '监狱时间',
            'CrimeProbability': '犯罪概率',
            'CollegeGraduation': '大专毕业率',
            'UniversityGraduation': '大学毕业率',
            'ImportCost': '进口成本',
            'LoanInterest': '贷款利率',
            'BuildingLevelingCost': '建筑拆除成本',
            'ExportCost': '出口成本',
            'TaxiStartingFee': '出租车起步费',
            'IndustrialEfficiency': '工业效率',
            'OfficeEfficiency': '办公效率',
            'PollutionHealthAffect': '污染对健康的影响',
            'HospitalEfficiency': '医院效率',
            'Administration Building': '行政大楼',
            'Cargo Transport Station': '货物运输站',
            'Disaster Facility': '灾害设施',
            'Early Disaster Warning Syst': '早期灾害预警系统',
            'Emergency Generator': '应急发电机',
            'Emergency Shelter': '应急避难所',
            'Firewatch Tower': '火灾监控塔',
            'Garbage Facility': '垃圾处理设施',
            'Garbage Powered': '垃圾发电',
            'Ground Water Powered': '地下水发电',
            'Hospital': '医院',
            'Maintenance Depot': '维修车间',
            'Parking Facility': '停车设施',
            'Police Station': '警察局',
            'Post Facility': '邮局',
            'Research Facility': '研究设施',
            'Sewage Outlet': '污水排放口',
            'Telecom Facility': '电信设施',
            'Traffic Spawner': '交通生成器',
            'Transport Depot': '运输车间',
            'Water Powered': '水力发电',
            'Water Tower': '水塔',
            'Welfare Office': '社会保障局',
            'Wind Powered': '风力发电',
            'Traded Resources': '交易资源',
            'Transports': '运输',
            'Loading Factor': '装载系数',
            'Transport Interval': '运输间隔',
            'Activation Threshold': '激活阈值',
            'Shelter Capacity': '庇护所容量',
            'Vehicle Capacity': '车辆容量',
            'Garbage Capacity': '垃圾容量',
            'Transport Capacity': '运输容量',
            'Processing Speed': '处理速度',
            'Industrial Waste Only': '仅限工业废物',
            'Production Per Unit': '每单位生产',
            'Maximum Ground Water': '最大地下水',
            'Ambulance Capacity': '救护车容量',
            'Medical Helicopter Capacity': '医疗直升机容量',
            'Patient Capacity': '病人容量',
            'Treatment Bonus': '治疗奖励',
            'Health Range': '健康范围',
            'Treat Diseases': '治疗疾病',
            'Treat Injuries': '治疗伤害',
            'Maintenance Type': '维护类型',
            'Garage Marker Capacity': '车库标记容量',
            'Patrol Car Capacity': '巡逻车容量',
            'Police Helicopter Capacity': '警用直升机容量',
            'Jail Capacity': '监狱容量',
            'Patrol': '巡逻',
            'Emergency': '应急',
            'Intelligence': '情报',
            'Post Van Capacity': '邮政面包车容量',
            'Post Truck Capacity': '邮政卡车容量',
            'Mail Storage Capacity': '邮件存储容量',
            'Mail Box Capacity': '邮箱容量',
            'Sorting Rate': '分拣速率',
            'Allow Submerged': '允许水下',
            'Network Capacity': '网络容量',
            'Penetrate Terrain': '穿透地形',
            'Track Type': '轨道类型',
            'Spawn Rate': '生成速率',
            'No Slow Vehicles': '无缓慢车辆',
            'Energy Types': '能源类型',
            'Production Duration': '生产持续时间',
            'Maintenance Duration': '维护持续时间',
            'Dispatch Center': '调度中心',
            'Production Factor': '生产因子',
            'Capacity Factor': '容量因子',
            'Maximum Wind': '最大风速',
            'Rotation Range': '旋转范围',
            'Value': '价值',
            'Building Type': '建筑类型',
            'PowerPlant': '发电厂',
            'FreshWaterBuilding': '污水处理厂',
            'SewageBuilding': '污水处理厂',
            'StormWaterBuilding': '雨水处理厂',
            'TransportDepot': '交通仓库',
            'TransportStation': '交通站点',
            'GarbageFacility': '垃圾处理设施',
            'FireStation': '消防站',
            'PoliceStation': '警察局',
            'RoadMaintenanceDepot': '道路维护仓库',
            'PostFacility': '邮政设施',
            'TelecomFacility': '电信设施',
            'EmergencyShelter': '紧急避难所',
            'DisasterFacility': '灾难设施',
            'FirewatchTower': '防火观察塔',
            'DeathcareFacility': '死亡护理设施',
            'AdminBuilding': '行政建筑',
            'WelfareOffice': '社会保障局',
            'ResearchFacility': '研究设施',
            'ParkMaintenanceDepot': '公园维护仓库',
            'ParkingFacility': '停车设施',
            'ResidentialBuilding': '住宅建筑',
            'CommercialBuilding': '商业建筑',
            'IndustrialBuilding': '工业建筑',
            'OfficeBuilding': '办公楼',
            'SignatureResidential': '标志性住宅',
            'ExtractorBuilding': '采集器建筑',
            'SignatureCommercial': '标志性商业',
            'SignatureIndustrial': '标志性工业',
            'SignatureOffice': '标志性办公',
            'LandValueSources': '土地价值来源',
            'EUCommercialHigh': '欧洲高级商业',
            'EUCommercialLow': '欧洲低级商业',
            'EUResidentialHigh': '欧洲高级住宅',
            'EUResidentialLow': '欧洲低级住宅',
            'EUResidentialLowWaterfront': '欧洲低级住宅（水边）',
            'EUResidentialMedium': '欧洲中级住宅',
            'EUResidentialMediumRow': '欧洲中级住宅（排屋）',
            'EUResidentialMixed': '欧洲混合住宅',
            'IndustrialAgriculture': '工业农业',
            'IndustrialForestry': '工业林业',
            'IndustrialManufacturing': '工业制造',
            'IndustrialOil': '工业石油',
            'IndustrialOre': '工业矿石',
            'NACommercialHigh': '北美高级商业',
            'NACommercialLow': '北美低级商业',
            'NAResidentialHigh': '北美高级住宅',
            'NAResidentialLow': '北美低级住宅',
            'NAResidentialLowWaterfront': '北美低级住宅（水边）',
            'NAResidentialMedium': '北美中级住宅',
            'NAResidentialMediumRow': '北美中级住宅（排屋）',
            'NAResidentialMixed': '北美混合住宅',
            'OfficeHigh': '高级办公楼',
            'OfficeLow': '低级办公楼',
            'ResidentialLowRent': '住宅低租金',
            'Unzoned': '未划分区域',
            'GroundPollutionMultiplier': '地面污染乘数',
            'AirPollutionMultiplier': '空气污染乘数',
            'NoisePollutionMultiplier': '噪音污染乘数',
            'Consumptions': '消耗量',
            'Consumption': '消耗',
            'ProductionRate': '生产速率',
            'UnlockEventImage': '解锁事件图片',
            'LocalizationID': '本地化ID',
            'MaleID': '男性ID',
            'FemaleID': '女性ID',
            'Brand': '品牌',
            'DistanceRange': '距离范围',
            'FireHazard': '火灾危险',
            'StructuralIntegrity': '结构完整性',
            'FloatingOffset': '浮动偏移',
            'FixedToBottom': '固定在底部',
            'HoveringHeight': '悬浮高度',
            'Left': '左',
            'Right': '右',
            'Straight': '直线',
            'Merge': '合并',
            'Gentle': '缓和',
            'Square': '正方形',
            'UTurn': 'U型转弯',
            'SetCompositionState': '设置组成状态',
            'RequireRoad': '需要道路',
            'TrackPassThrough': '轨道穿越',
            'TradedResources': '交易资源',
            'Commuting': '通勤',
            'TransferType': '转移类型',
            'Remoteness': '偏远度',
            'VerticalPillarOffsetRange': '垂直柱偏移范围',
            'Vertical': '垂直',
            'Horizontal': '水平',
            'Standalone': '独立',
            'Base': '基础',
            'RandomizeGroupIndex': '随机化组索引',
            'MapFeature': '地图特征',
            'Area': '区域',
            'BuildableLand': '可建造土地',
            'FertileLand': '肥沃土地',
            'Forest': '森林',
            'GroundWater': '地下水',
            'RequireEmpty': '需要空地',
            'RequireRenter': '需要租户',
            'RequireGoodWealth': '需要良好财富',
            'RequireDogs': '需要狗',
            'RequireHomeless': '需要无家可归者',
            'RequireChildren': '需要儿童',
            'RequireTeens': '需要青少年',
            'VehicleLeft': '左侧车辆',
            'VehicleRight': '右侧车辆',
            'CrossingLeft': '左侧人行横道',
            'CrossingRight': '右侧人行横道',
            'AllowFlipped': '允许翻转',
            'ReachOffset': '达到偏移',
            'Stop': '停止',
            'Yield': '让行',
            'NoTurnLeft': '禁止左转',
            'NoTurnRight': '禁止右转',
            'NoUTurnLeft': '禁止左转弯',
            'NoUTurnRight': '禁止右转弯',
            'DoNotEnter': '禁止通行',
            'Motorway': '高速公路',
            'Oneway': '单行道',
            'SpeedLimit': '速度限制',
            'BusOnly': '仅公交',
            'TaxiOnly': '仅出租车',
            'RoundaboutCounterclockwise': '逆时针环岛',
            'RoundaboutClockwise': '顺时针环岛',
            'UtilityType': '公用事业类型',
            'UtilityPosition': '公用事业位置',
            'WaterPipe': '给水管道',
            'SewagePipe': '污水管道',
            'StormwaterPipe': '雨水管道',
            'LowVoltageLine': '低电压线路',
            'Fence': '围栏',
            'Catenary': '接触网',
            'HighVoltageLine': '高电压线路',
            'Polluted': '受污染的',
            'RequireSnow': '需要雪',
            'ForbidSnow': '禁止雪',
            'LandmarkBuildings': '地标建筑',
            'SanFranciscoSet': '旧金山套装',
            'ReplaceWith': '替换为',
            'MailCapacity': '邮件容量',
            'AccessConnectionType': '接入连接类型',
            'RouteConnectionType': '路线连接类型',
            'AccessTrackType': '接入轨道类型',
            'RouteTrackType': '路线轨道类型',
            'AccessRoadType': '接入道路类型',
            'RouteRoadType': '路线道路类型',
            'EnterDistance': '进入距离',
            'ExitDistance': '退出距离',
            'AccessDistance': '接入距离',
            'BoardingTime': '上车时间',
            'LoadingFactor': '装载因子',
            'PassengerTransport': '乘客运输',
            'CargoTransport': '货物运输',
            'Theme': '主题',
            'Achievements': '成就',
            'Early Disaster Warning System': '灾害预警系统',
            'Modifiers': '修改器',
            'Multiplier': '倍增器',
            'Upkeep Modifier': '维护费修改器',
            'Section': '部分',
            'Edge States': '边缘状态',
            'Node States': '节点状态',
            'Net Sub Objects': '道路子对象',
            'Net Upgrade': '道路升级',
            'Overhead Net Sections': '车道覆盖',
            'Fixed Index': '固定索引',
            'Net': '道路',
            'Unset State': '未设置状态',
            'Ambulance': '救护车',
            'Car Tractor': '车载拖拉机',
            'Cargo Transport': '货物运输',
            'Delivery Truck': '送货卡车',
            'Fire Engine': '消防车',
            'Garbage Truck': '垃圾车',
            'Hearse': '灵车',
            'Maintenance Vehicle': '维修车辆',
            'Police Car': '警车',
            'Post Van': '邮政货车',
            'Work Vehicle': '工作车辆',
            'Cargo Capacity': '货物容量',
            'Max Resource Count': '最大资源数量',
            'Transported Resources': '运输资源',
            'Trailer Type': '拖车类型',
            'Fixed Trailer': '固定拖车',
            'Towbar': '拖车连接器',
            'Semi': '半挂车',
            'Fixed': '固定',
            'Extinguishing Rate': '灭火速率',
            'Extinguishing Spread': '灭火传播',
            'Extinguishing Capacity': '灭火容量',
            'Destroyed Clear Duration': '清除被毁持续时间',
            'Unload Rate': '卸货速率',
            'Maintenance Capacity': '维护容量',
            'Maintenance Rate': '维护速率',
            'Criminal Capacity': '罪犯容量',
            'Crime Reduction Rate': '犯罪减少率',
            'Shift Duration': '换班持续时间',
            'Mail Capacity': '邮件容量',
            'Work Type': '工作类型',
            'Map Feature': '地图特征',
            'Max Work Amount': '最大工作量',
            'Lot Prefab': '地块预制体',
            'Color': '颜色',
            'Edge Color': '边缘颜色',
            'Selection Color': '选中颜色',
            'Selection Edge Color': '选中边缘颜色',
            'Max Radius': '最大半径',
            'Range Color': '范围颜色',
            'Area Sub Objects': '区域子对象',
            'Enclosed Area': '封闭区域',
            'Extractor Area': '提取区域',
            'Hangaround Area': '闲逛区域',
            'Master Area': '主区域',
            'Navigation Area': '导航区域',
            'Placeholder Area': '占位符区域',
            'Rendered Area': '渲染区域',
            'Spawnable Area': '可生成区域',
            'Storage Area': '存储区域',
            'Terrain Area': '地形区域',
            'Border Lane Type': '边界车道类型',
            'Counter Clock Wise': '逆时针',
            'Activities': '活动',
            'Slave Areas': '从区域',
            'Secondary Type': '次要类型',
            'Roundness': '圆滑度',
            'Lod Bias': 'LOD偏差',
            'Renderer Priority': '渲染器优先级',
            'Decal Layer Mask': '贴花层遮罩',
            'Terrain': '地形',
            'Creatures': '生物',
            'Stored Resources': '存储资源',
            'Slope Width': '坡宽',
            'Noise Scale': '噪声比例',
            'Noise Factor': '噪声因子',
            'Surface Prefab': '表面预制体',
            'Vertical Pillar Offset Range': '垂直柱偏移范围',
            'Content Prerequisite': '内容先决条件',
            'Manual Unlockable': '手动可解锁',
            'Walk Speed': '步行速度',
            'Run Speed': '奔跑速度',
            'Resident': '居民',
            'Age': '年龄',
            'Width': '宽度',
            'Depth': '深度',
            'Up Keep Cost': '维护成本',
            'Asset Stamp Prefab': '资产图章预制体',
            'Layer': '图层',
            'Default': '默认',
            'Fence Prefab': '栅栏预制体',
            'Ground Max Speed': '地面最大速度',
            'Ground Acceleration': '地面加速度',
            'Ground Braking': '地面制动',
            'Ground Turning': '地面转向',
            'Flying Speed': '飞行速度',
            'Flying Acceleration': '飞行加速度',
            'Flying Braking': '飞行制动',
            'Flying Turning': '飞行转向',
            'Flying Angular Acceleration': '飞行角加速度',
            'Climb Angle': '攀爬角度',
            'Slow Pitch Angle': '缓慢俯仰角',
            'Turning Roll Factor': '转向滚动系数',
            'Airplane Prefab': '飞机预制体',
            'Train Car Prefab': '火车车厢预制体',
            'Bogie Offset': '转向架偏移',
            'Angular Acceleration': '角加速度',
            'Watercraft Prefab': '水上交通工具预制体',
            'Multiple Unit Train Car Prefab': '多节火车车厢预制体',
            'Min Multiple Unit Count': '最小多节车辆数量',
            'Max Multiple Unit Count': '最大多节车辆数量',
            'Carriages': '车厢',
            'Carriage': '车厢',
            'Min Count': '最小数量',
            'Max Count': '最大数量',
            'Add Reversed End Carriage': '添加反向尾部车厢',
            'Car Trailer Prefab': '汽车拖车预制体',
            'Object Mesh Info': '物体网格信息',
            'Render Prefab': '渲染预制体',
            'Color Properties': '颜色属性',
            'Color Variations': '颜色变化',
            'Channels Binding': '通道绑定',
            'Variation Groups': '变体组',
            'Variation Ranges': '变体范围',
            'Alpha Ranges': 'Alpha 范围',
            'External Color Source': '外部颜色来源',
            'Colors': '颜色',
            'Variation Group': '变体组',
            'Channel Id': '通道标识',
            'Can Be Modified By External': '可由外部修改',
            'Emissive Properties': '发光属性',
            'Single Lights': '单个灯光',
            'Multi Lights': '多个灯光',
            'Signal Group Animations': '信号组动画',
            'Purpose': '目的',
            'Color Off': '关闭时颜色',
            'Luminance': '亮度',
            'Response Time': '响应时间',
            'Materialld': '材料 ID',
            'Base Properties': '基本属性',
            'Base Type': '基本类型',
            'Use Min Bounds': '使用最小边界',
            'Latitude': '纬度',
            'Longitude': '经度',
            'FreezingTemperature': '冰点温度',
            'DefaultWeather': '默认天气',
            'DefaultWeathers': '默认天气',
            'Seasons': '季节',
            'Prefab': '预制体',
            'Name ID': '名称 ID',
            'Icon Path': '图标路径',
            'Start Time': '开始时间',
            'Temp Night Day': '夜间白天温度',
            'Temp Deviation Night Day': '夜间白天温度偏差',
            'Cloud Chance': '云量几率',
            'Cloud Amount': '云量',
            'Cloud Amount Deviation': '云量偏差',
            'Precipitation Chance': '降水几率',
            'Precipitation Amount': '降水量',
            'Precipitation Amount Deviation': '降水量偏差',
            'Turbulence': '湍流',
            'Aurora Amount': '极光数量',
            'Aurora Chance': '极光几率',
            'Edit Climate': '编辑气候',
            'Load climate prefab…': '加载气候预制体...',
            'External Lot': '外部地块',
            'Override Lot Size': '覆盖地块尺寸',
            'Override Height': '覆盖高度',
            'Vehicle Left': '车辆左侧',
            'Vehicle Right': '车辆右侧',
            'Crossing Left': '交叉左侧',
            'Crossing Right': '交叉右侧',
            'Allow Flipped': '允许翻转',
            'Reach Offset': '到达偏移',
            'Effect Settings': '效果设置',
            'Object Sub Object Info': '对象子对象信息',
            'Fire Hazard': '火灾危险',
            'Structural Integrity': '结构完整性',
            'Segment Length': '段长度',
            'Hanging': '悬挂',
            'Water Flow': '水流',
            'Count Range': '计数范围',
            'Length': '长度',
            'Can Curve': '可弯曲',
            'Conditions': '条件',
            'Required Flags': '必要标志',
            'Forbidden Flags': '禁止标志',
            'Intensity Flags': '强度标志',
            'Disable Distance Culling': '禁用距离剔除',
            'Parked': '停放',
            'Operational': '运行',
            'OnFire': '着火',
            'Extinguishing': '灭火',
            'TakingOff': '起飞',
            'Landing': '着陆',
            'Flying': '飞行',
            'Stopped': '停止',
            'Processing': '处理中',
            'Boarding': '登机',
            'Disaster': '灾难',
            'Occurring': '发生',
            'Night': '夜晚',
            'LightsOff': '熄灯',
            'MainLights': '主灯',
            'ExtraLights': '额外灯光',
            'WarningLights': '警示灯',
            'WorkLights': '工作灯光',
            'Collapsing': '坍塌',
            'Last': '最后',
            'Volume': '音量',
            'Pitch': '音高',
            'Spatial Blend': '空间混合',
            'Doppler': '多普勒效应',
            'Spread': '扩散',
            'Rolloff Mode': '衰减模式',
            'Min Max Distance': '最小/最大距离',
            'Loop': '循环',
            'Mixer Group': '混音器组',
            'Rolloff Curve': '衰减曲线',
            'Source Size': '源尺寸',
            'Fade Times': '淡入淡出时间',
            'Random Start Time': '随机开始时间',
            'Logarithmic': '对数',
            'Linear': '线性',
            'Custom': '自定义',
            'Randomize Group Index': '随机化组索引',
            'Connection Type 1': '连接类型 1',
            'Connection Type 2': '连接类型 2',
            'Takeoff Location': '起飞位置',
            'Floating Offset': '浮动偏移',
            'Fixed To Bottom': '固定到底部',
            'Movement Type': '移动类型',
            'Fixed Tractor': '固定牵引机',
            'Free': '自由',
            'Locked': '锁定',
            'Utility Type': '实用类型',
            'Utility Position': '实用位置',
            'Require Road': '需要道路',
            'Track Pass Through': '轨道穿越',
            'Set Composition State': '设置组合状态',
            'Flying Animal': '飞行动物',
            'Pet': '宠物',
            'Swimming Animal': '水生动物',
            'Wildlife': '野生动物'
        }

            , 编辑器.通用inc, {
            'Element ': '元素',
            'EU_ChimneyStyle0': '欧洲烟囱风格0',
            'EU_FenceResidentialPieceStyle0': '欧洲住宅围栏块风格0',
            'EU_WallPylonStyle0': '欧洲墙体支架风格0',
            'EU_WindowGuardRailingStyle0': '欧洲窗户护栏风格0',
            'EU_WindowHatchStyle0': '欧洲窗户舱口风格0',
            'EU_WindowOrnamentStyle0': '欧洲窗户装饰风格0',
            'FencelndustrialHighStyle0': '工业围栏高风格0',
            'FencelndustrialLowStyle0': '工业围栏低风格0',
            'FenceResidentialHighStyle0': '住宅围栏高风格0',
            'FenceResidentialLowStyle0': '住宅围栏低风格0',
            'FireEscapeStyle0': '消防逃生梯风格0',
            'GymParkStyle0': '健身公园风格0',
            'LadderStyle0': '梯子风格0',
            'LightpoleParkStyle0': '公园路灯风格0',
            'LogPileStyle0': '圆木堆风格0',
            'NA_ChimneyResidentialStyle0': '北美住宅烟囱风格0',
            'NA_FenceResidentialPieceStyle0': '北美住宅围栏块风格0',
            'NA_WindowHatchStyle0': '北美窗户舱口风格0',
            'OutdoorSofaStyle0': '户外沙发风格0',
            'PergolaStyle0': '凉亭风格0',
            'SkateParkStyle0': '滑板公园风格0',
            'SportParkStyle0': '体育公园风格0',
            'StaircaseSpiralStyle0': '螺旋楼梯风格0',
            'StreetLightStyle0': '路灯风格0',
            'TableSetCommercialStyle0': '商业桌椅组风格0',
            'TableSetStyle0': '桌椅组风格0',
            'TennisCourtStyle0': '网球场风格0',
            'VentilationDuctStyle0': '通风管道风格0'
        },
            编辑器.label, {
            'Traffic Lights': '交通信号灯',
            'Service Object': '服务对象',
            'Service': '服务',
        }
        )
    },
    MouseEvent: async() => {
        console.log('Editor')
        if (!on.Editor) { return }
        await delay(400)
        I18(['Editor'])
    }
}

